### PR TITLE
Move logstash filters into PaaS Tech Docs

### PR DESCRIPTION
**Pull request by 46bit**
Hi. We've added [instructions for using Logit.io](https://docs.cloud.service.gov.uk/#set-up-the-logit-io-log-management-service) to the Tech Docs for the GOV.UK PaaS (which is built on Cloud Foundry.)

We can now refer people to our Tech Docs for these instructions, rather than using the very brief explanation currently provided in the GDS Way. This PR removes the previous instructions and instead links to our expanded version.

### CODE REVIEW

**Comment by 46bit** [comment]
We want to discuss internally where to link to, so I've retitled this to a `WIP` and please don't merge this for now.

**Comment by philandstuff** [comment]
Thanks for this! 👍 in principle and I look forward to the PR when it's ready.

**Comment by chrisfarms** [comment]
Our docs have now been merged and the link has stayed as-is so this PR is good to go.

I cannot remove the WIP from the title since @46bit raised from his personal account 😭

**Comment by philandstuff** [comment]
@chrisfarms huh. I managed to remove WIP from the title 😄

**Comment by 46bit** [comment]
@chrisfarms Sorry about that--I wasn't sure about making a `paas-gds-way` repository and couldn't think of a better option.

**Pull request merged**
